name: Output Github Context on Issues creation
on:
  issues:
    types: [opened, edited]

jobs:
  outputContext:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "Entire Github Context ${{ toJson(github) }}"
